loglevel: info
debug: false
binadata: false
https: false
host: 0.0.0.0
port: 80
admin:
  username: username
  rolename: admin
  roledisplayname: roledisplayname
  name: name
  password: password
db:
  adapter: mysql # mysql postgres sqlite3
  host: mysql
  port: 3306
  name: database_name
  user: root
  password: password
redis:
  host: redis
  port: 6379
  pwd: password